// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJldwkzvXFbOt6Z5FYQYjxxjGzbAfItc',
    appId: '1:633918414762:web:8b4431bd1b847e932655d3',
    messagingSenderId: '633918414762',
    projectId: 'hr-employee-app-9aca8',
    authDomain: 'hr-employee-app-9aca8.firebaseapp.com',
    storageBucket: 'hr-employee-app-9aca8.firebasestorage.app',
    measurementId: 'G-XGX0JR2T98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA66QZhHR4cgbmrfolZeskwuMgfZWAsjek',
    appId: '1:633918414762:android:0119702e69999e572655d3',
    messagingSenderId: '633918414762',
    projectId: 'hr-employee-app-9aca8',
    storageBucket: 'hr-employee-app-9aca8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAj9F7QGStLcTS4TP2vZzdSTD1ZGnNM8M',
    appId: '1:633918414762:ios:75c727c61f0e41bd2655d3',
    messagingSenderId: '633918414762',
    projectId: 'hr-employee-app-9aca8',
    storageBucket: 'hr-employee-app-9aca8.firebasestorage.app',
    iosBundleId: 'com.hr.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAj9F7QGStLcTS4TP2vZzdSTD1ZGnNM8M',
    appId: '1:633918414762:ios:f8a1fbacff7357bb2655d3',
    messagingSenderId: '633918414762',
    projectId: 'hr-employee-app-9aca8',
    storageBucket: 'hr-employee-app-9aca8.firebasestorage.app',
    iosBundleId: 'com.example.hrEmployeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJldwkzvXFbOt6Z5FYQYjxxjGzbAfItc',
    appId: '1:633918414762:web:dac80841ccf999f62655d3',
    messagingSenderId: '633918414762',
    projectId: 'hr-employee-app-9aca8',
    authDomain: 'hr-employee-app-9aca8.firebaseapp.com',
    storageBucket: 'hr-employee-app-9aca8.firebasestorage.app',
    measurementId: 'G-N9B8FPQWD9',
  );

}