// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI6Z4f5by1bZAjLcCaKP3TLS_XQRP3k5c',
    appId: '1:281767469313:web:2334314471f6144f533b00',
    messagingSenderId: '281767469313',
    projectId: 'retail-support-co',
    authDomain: 'retail-support-co.firebaseapp.com',
    storageBucket: 'retail-support-co.firebasestorage.app',
    measurementId: 'G-67038WX6B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlr74-5buCwByeKHyPuFeh1-1VGT0M2Ik',
    appId: '1:281767469313:android:b96c7f36dbba6507533b00',
    messagingSenderId: '281767469313',
    projectId: 'retail-support-co',
    storageBucket: 'retail-support-co.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_K61PxyaZp7OMjMPo2DNS-TNYqhxcFqI',
    appId: '1:281767469313:ios:c2433d86cb2d43bb533b00',
    messagingSenderId: '281767469313',
    projectId: 'retail-support-co',
    storageBucket: 'retail-support-co.firebasestorage.app',
    iosBundleId: 'com.example.hrEmployeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_K61PxyaZp7OMjMPo2DNS-TNYqhxcFqI',
    appId: '1:281767469313:ios:c2433d86cb2d43bb533b00',
    messagingSenderId: '281767469313',
    projectId: 'retail-support-co',
    storageBucket: 'retail-support-co.firebasestorage.app',
    iosBundleId: 'com.example.hrEmployeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI6Z4f5by1bZAjLcCaKP3TLS_XQRP3k5c',
    appId: '1:281767469313:web:6f3d5962e324e651533b00',
    messagingSenderId: '281767469313',
    projectId: 'retail-support-co',
    authDomain: 'retail-support-co.firebaseapp.com',
    storageBucket: 'retail-support-co.firebasestorage.app',
    measurementId: 'G-SL5E6K7CGH',
  );

}